-------------------------------------------------------------------------
-- Design unit: R8 simutation test bench
-- Description: R8 processor connected to a BRAM memory
--      The BRAM memory is able to load image files generated by the R8 simulator             
-------------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;        

entity R8_BRAM_tb is
end R8_BRAM_tb;

architecture testbench of R8_BRAM_tb is
    
      signal clk : std_logic := '0';  
      signal rst: std_logic;
      signal display_enable : std_logic_vector(3 downto 0);    
      signal display_data   : std_logic_vector(7 downto 0);
    
begin
    
    R8_BRAM_BLOCK: entity work.R8_BRAM(structural) 
        port map (
            board_clock     => clk,
            board_rst       => rst,
            display_en_n    => display_enable,     --7 segment display interface
            display_data    => display_data
        );
        
    -- Generates the clock signal            
    clk <= not clk after 10 ns;
    
    -- Generates the reset signal
    rst <='1', '0' after 5 ns;        
    
end testbench;
