onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -label clk /r8_crypto/clk
add wave -noupdate -divider crypto
add wave -noupdate -label data_in /r8_crypto/Crypto/data_in
add wave -noupdate -label data_out /r8_crypto/Crypto/data_out
add wave -noupdate -label data_av /r8_crypto/Crypto/data_av
add wave -noupdate -label keyExg /r8_crypto/Crypto/keyExchange
add wave -noupdate -label eom /r8_crypto/Crypto/eom
add wave -noupdate -color Orange -label ack /r8_crypto/Crypto/ack
add wave -noupdate -color Gold -label tristate /r8_crypto/R8_uC/port_io(15)
add wave -noupdate -divider memory
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1000)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1001)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1002)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1003)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1004)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1005)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1006)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1007)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1008)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1009)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1010)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1011)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1012)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1013)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1014)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1015)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1016)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1017)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1018)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1019)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1020)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1021)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1022)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1023)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1024)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1025)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1026)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1027)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1028)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1029)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1030)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1031)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1032)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1033)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1034)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1035)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1036)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1037)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1038)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1039)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1040)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1041)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1042)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1043)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1044)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1045)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1046)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1047)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1048)
add wave -noupdate -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1049)
add wave -noupdate -divider variables
add wave -noupdate -label size -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1050)
add wave -noupdate -label random_x -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1051)
add wave -noupdate -label crypto_key -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1052)
add wave -noupdate -label index -radix decimal -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1053)
add wave -noupdate -divider MSG
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1054)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1055)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1056)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1057)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1058)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1059)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1060)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1061)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1062)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1063)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1064)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1065)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1066)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1067)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1068)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1069)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1070)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1071)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1072)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1073)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1074)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1075)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1076)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1077)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1078)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1079)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1080)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1081)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1082)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1083)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1084)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1085)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1086)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1087)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1088)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1089)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1090)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1091)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1092)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1093)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1094)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1095)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1096)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1097)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1098)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1099)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1100)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1101)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1102)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1103)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1104)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1105)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1106)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1107)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1108)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1109)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1110)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1111)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1112)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1113)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1114)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1115)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1116)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1117)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1118)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1119)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1120)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1121)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1122)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1123)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1124)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1125)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1126)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1127)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1128)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1129)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1130)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1131)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1132)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1133)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1134)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1135)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1136)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1137)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1138)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1139)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1140)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1141)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1142)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1143)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1144)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1145)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1146)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1147)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1148)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1149)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1150)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1151)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1152)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1153)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1154)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1155)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1156)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1157)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1158)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1159)
add wave -noupdate -radix ascii -radixenum symbolic -radixshowbase 0 /r8_crypto/R8_uC/RAM/RAM(1160)
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1350297 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {3948497664 ps}
