onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -label rst /r8_crypto_tb/r8_crypto/rst
add wave -noupdate -divider R8
add wave -noupdate -color Blue -label decodedInstruction /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/decodedInstruction
add wave -noupdate -color {Medium Sea Green} -label State /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/currentState
add wave -noupdate -color Sienna -label regPC /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/regPC
add wave -noupdate -color {Medium Orchid} -label regSP /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/regSP
add wave -noupdate -label regIR /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/regIR
add wave -noupdate -label regISRA /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/regISRA
add wave -noupdate -label HIGH /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/regHigh
add wave -noupdate -label LOW /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/regLow
add wave -noupdate -color Goldenrod -label registerFile -expand -subitemconfig {/r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(0) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(1) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(2) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(3) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(4) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(5) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(6) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(7) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(8) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(9) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(10) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(11) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(12) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(13) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(14) {-color Goldenrod -height 15} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile(15) {-color Goldenrod -height 15}} /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/registerFile
add wave -noupdate -label rw /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/rw
add wave -noupdate -label {ce mem} /r8_crypto_tb/r8_crypto/R8_uC/ce_mem
add wave -noupdate -label {ce io} /r8_crypto_tb/r8_crypto/R8_uC/ce_io
add wave -noupdate -divider Interruption
add wave -noupdate -color Magenta -label Request /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/intr
add wave -noupdate -color Wheat -label Status /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/InterruptionStatus
add wave -noupdate -divider {memory interface}
add wave -noupdate -label data_in_r8 /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/data_in
add wave -noupdate -color {Dark Green} -label data_out_r8 /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/data_out
add wave -noupdate -color Aquamarine -label address /r8_crypto_tb/r8_crypto/R8_uC/PROCESSOR/address
add wave -noupdate -divider PIC
add wave -noupdate -label highPriorityRequest /r8_crypto_tb/r8_crypto/R8_uC/PIC/highPriorityReq
add wave -noupdate -label address /r8_crypto_tb/r8_crypto/R8_uC/PIC/address
add wave -noupdate -label data /r8_crypto_tb/r8_crypto/R8_uC/PIC/data
add wave -noupdate -label {ce PIC} /r8_crypto_tb/r8_crypto/R8_uC/ce_PIC
add wave -noupdate -label wr /r8_crypto_tb/r8_crypto/R8_uC/PIC/wr
add wave -noupdate -label {irq reg} /r8_crypto_tb/r8_crypto/R8_uC/PIC/irq_reg
add wave -noupdate -label mask /r8_crypto_tb/r8_crypto/R8_uC/PIC/mask
add wave -noupdate -divider portA
add wave -noupdate -label rw /r8_crypto_tb/r8_crypto/R8_uC/PORT_A/wr
add wave -noupdate -label {ce portA} /r8_crypto_tb/r8_crypto/R8_uC/ce_portA
add wave -noupdate -color {Medium Spring Green} -label PortData /r8_crypto_tb/r8_crypto/R8_uC/PORT_A/PortData
add wave -noupdate -color {Steel Blue} -label PortConfig /r8_crypto_tb/r8_crypto/R8_uC/PORT_A/PortConfig
add wave -noupdate -color {Midnight Blue} -label PortEnable /r8_crypto_tb/r8_crypto/R8_uC/PORT_A/PortEnable
add wave -noupdate -color Blue -label PortIrqEnable /r8_crypto_tb/r8_crypto/R8_uC/PORT_A/PortIrqEnable
add wave -noupdate -divider Cryptos
add wave -noupdate -label op /r8_crypto_tb/r8_crypto/op
add wave -noupdate -label id /r8_crypto_tb/r8_crypto/id
add wave -noupdate -label ack /r8_crypto_tb/r8_crypto/ack
add wave -noupdate -divider {Crypto 0}
add wave -noupdate -format Event /r8_crypto_tb/r8_crypto/Crypto0/rst
add wave -noupdate -format Event /r8_crypto_tb/r8_crypto/Crypto0/ack
add wave -noupdate -format Event /r8_crypto_tb/r8_crypto/Crypto0/data_in
add wave -noupdate -format Event /r8_crypto_tb/r8_crypto/Crypto0/data_out
add wave -noupdate -format Event /r8_crypto_tb/r8_crypto/Crypto0/data_av
add wave -noupdate -format Event /r8_crypto_tb/r8_crypto/Crypto0/keyExchange
add wave -noupdate -format Event /r8_crypto_tb/r8_crypto/Crypto0/eom
add wave -noupdate -divider {Crypto 1}
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto1/rst
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto1/ack
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto1/data_in
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto1/data_out
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto1/data_av
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto1/keyExchange
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto1/eom
add wave -noupdate -divider {Crypto 2}
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto2/rst
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto2/ack
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto2/data_in
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto2/data_out
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto2/data_av
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto2/keyExchange
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto2/eom
add wave -noupdate -divider {Crypto 3}
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto3/rst
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto3/ack
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto3/data_in
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto3/data_out
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto3/data_av
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto3/keyExchange
add wave -noupdate /r8_crypto_tb/r8_crypto/Crypto3/eom
add wave -noupdate -divider {MSG 0}
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1071)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1072)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1073)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1074)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1075)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1076)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1077)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1078)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1079)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1080)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1081)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1082)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1083)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1084)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1085)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1086)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1087)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1088)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1089)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1090)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1091)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1092)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1093)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1094)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1095)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1096)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1097)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1098)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1099)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1100)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1101)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1102)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1103)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1104)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1105)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1106)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1107)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1108)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1109)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1110)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1111)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1112)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1113)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1114)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1115)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1116)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1117)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1118)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1119)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1120)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1121)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1122)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1123)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1124)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1125)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1126)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1127)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1128)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1129)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1130)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1131)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1132)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1133)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1134)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1135)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1136)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1137)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1138)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1139)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1140)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1141)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1142)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1143)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1144)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1145)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1146)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1147)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1148)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1149)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1150)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1151)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1152)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1153)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1154)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1155)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1156)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1157)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1158)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1159)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1160)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1161)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1162)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1163)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1164)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1165)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1166)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1167)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1168)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1169)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1170)
add wave -noupdate -divider {MSG 1}
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1171)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1172)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1173)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1174)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1175)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1176)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1177)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1178)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1179)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1180)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1181)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1182)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1183)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1184)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1185)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1186)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1187)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1188)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1189)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1190)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1191)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1192)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1193)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1194)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1195)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1196)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1197)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1198)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1199)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1200)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1201)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1202)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1203)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1204)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1205)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1206)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1207)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1208)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1209)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1210)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1211)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1212)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1213)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1214)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1215)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1216)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1217)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1218)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1219)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1220)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1221)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1222)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1223)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1224)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1225)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1226)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1227)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1228)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1229)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1230)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1231)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1232)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1233)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1234)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1235)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1236)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1237)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1238)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1239)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1240)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1241)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1242)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1243)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1244)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1245)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1246)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1247)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1248)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1249)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1250)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1251)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1252)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1253)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1254)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1255)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1256)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1257)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1258)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1259)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1260)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1261)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1262)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1263)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1264)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1265)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1266)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1267)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1268)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1269)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1270)
add wave -noupdate -divider {MSG 2}
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1271)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1272)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1273)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1274)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1275)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1276)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1277)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1278)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1279)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1280)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1281)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1282)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1283)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1284)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1285)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1286)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1287)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1288)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1289)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1290)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1291)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1292)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1293)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1294)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1295)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1296)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1297)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1298)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1299)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1300)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1301)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1302)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1303)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1304)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1305)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1306)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1307)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1308)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1309)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1310)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1311)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1312)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1313)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1314)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1315)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1316)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1317)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1318)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1319)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1320)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1321)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1322)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1323)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1324)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1325)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1326)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1327)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1328)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1329)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1330)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1331)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1332)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1333)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1334)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1335)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1336)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1337)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1338)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1339)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1340)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1341)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1342)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1343)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1344)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1345)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1346)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1347)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1348)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1349)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1350)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1351)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1352)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1353)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1354)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1355)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1356)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1357)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1358)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1359)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1360)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1361)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1362)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1363)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1364)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1365)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1366)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1367)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1368)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1369)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1370)
add wave -noupdate -divider {MSG 3}
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1371)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1372)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1373)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1374)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1375)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1376)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1377)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1378)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1379)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1380)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1381)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1382)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1383)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1384)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1385)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1386)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1387)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1388)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1389)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1390)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1391)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1392)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1393)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1394)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1395)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1396)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1397)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1398)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1399)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1400)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1401)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1402)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1403)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1404)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1405)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1406)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1407)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1408)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1409)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1410)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1411)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1412)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1413)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1414)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1415)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1416)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1417)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1418)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1419)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1420)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1421)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1422)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1423)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1424)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1425)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1426)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1427)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1428)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1429)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1430)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1431)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1432)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1433)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1434)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1435)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1436)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1437)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1438)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1439)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1440)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1441)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1442)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1443)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1444)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1445)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1446)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1447)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1448)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1449)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1450)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1451)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1452)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1453)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1454)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1455)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1456)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1457)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1458)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1459)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1460)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1461)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1462)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1463)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1464)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1465)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1466)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1467)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1468)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1469)
add wave -noupdate -radix ascii -radixshowbase 0 /r8_crypto_tb/r8_crypto/R8_uC/RAM/RAM(1470)
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {950800398 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 149
configure wave -valuecolwidth 65
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {7931259989 ps}
